# Generated by Django 4.2.4 on 2024-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_userclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
