# Generated by Django 4.2.4 on 2024-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
