# Generated by Django 4.2.4 on 2024-08-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='gallery.userclient'),
        ),
    ]
